version: "3.7"

services:
  fluent-bit:
    image: fluent/fluent-bit:2.2.2
    container_name: fluent-bit
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ./alog1:/alog1:ro
      - ./alog2:/alog2:ro
    ports:
      - "2020:2020"  # optional: for health check API

volumes:
  esdata:

