filebeat.inputs:
  - type: filestream
    enabled: true
    paths:
      - /var/log/mountlog/f1.log

setup.kibana:
  host: "http://kibana:5601"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

